name: Scrape Data
on:
  schedule:
    - cron:  '0 */12 * * *' # Every 12 hours. Ref https://crontab.guru/examples.html
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run snap 
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main